//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFokina.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кулинария
    {
        public int ID { get; set; }
        public string Название_Блюда { get; set; }
        public Nullable<int> ID_Категории { get; set; }
        public string Рецепт { get; set; }
        public Nullable<int> Вес { get; set; }
        public string Продукты { get; set; }
        public Nullable<int> Калорийность { get; set; }
        public Nullable<int> Цена { get; set; }
        public Nullable<int> ID_Единиц { get; set; }
    
        public virtual Измерение Измерение { get; set; }
        public virtual Категория Категория { get; set; }
    }
}
